#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env_leveleditor = env.Clone()

env_leveleditor.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
    env_leveleditor.add_source_files(env.modules_sources, "editor/*.cpp")
    env_leveleditor.add_source_files(env.modules_sources, "editor/tools/*.cpp")
    env_leveleditor.add_source_files(env.modules_sources, "editor/dock/*.cpp")
